name: UMN
description: Plugin for UMN Minecraft Server
main: dev.chezy.umn.UMN
author: chez
version: 0.1
api-version: 1.16
depend: [SidebarAPI, Essentials]
commands:
    verify:
        description: Verifies a player
        usage: /<command>
    test:
        description: things
        usage: /<command>
    recipe:
        description: Shows recipes from this plugin
        usage: /<command>
    beds:
        description: Shows all of your beds
        usage: /<command>
    xpbottle:
        description: Extracts XP from your player
        usage: /<command>
    xp:
        description: Shows your current XP
        usage: /<command>
    help:
        description: Shows server help page
        usage: /<command>
    plugins:
        description: Shows enabled plugins
        usage: /<command>
        aliases: [pl]